[package]
name = "riot-repl"
version = "0.0.32"
description = "REPL support for Riot tooling"
license = "Apache-2.0"
public = false

[lib]
path = "src/Riot_repl.ml"

[dependencies]
kernel = { path = "../kernel", version = "*" }
std = { path = "../std", version = "*" }
riot-eval = { path = "../riot-eval", version = "*" }
riot-model = { path = "../riot-model", version = "*" }
tty = { path = "../tty", version = "*" }
